name: Code Review

on: 
  pull_request_target:
    types: [opened, edited, reopened, synchronize, ready_for_review, unlocked, review_requested]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: deps, build, and test
        run: |
          yarn
          yarn run build
          yarn run test:unit
        env:
          CI: true
      - name: Danger
        run: npx danger ci --text-only -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  mergepal-merge:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v1
      - uses:  YasiOnFire/merge-pal-action@v0.5.2
        with:
          token: ${{ secrets.WF_GITHUB_TOKEN }}
